# Example configuration file with separate URLs and methods for status and priority
Types:
  - name: type1
    status:
      path: /status
      method: GET
      timeout: 2000
    priority:
      path: /status
      method: PUT
      timeout: 10000
      body: {}
      params: 
        primary: "new_state=primary"
        secondary: "new_state=secondary"
  - name: type2
    status:
      path: /status
      method: GET
      timeout: 2000
    priority:
      path: /state
      method: PUT
      timeout: 10000
      body:
        action: "set_priority"
      params: 
        primary: "new_state=primary"
        secondary: "new_state=secondary"
  - name: type3
    status:
      path: /status
      method: GET
      timeout: 2000
      body:
        include_details: true
        check_components: ["database", "cache", "storage"]
    priority:
      path: /state
      method: PUT
      timeout: 10000
      body:
        include_details: true
        check_components: ["database", "cache", "storage"]
      params: 
        primary: "new_state=primary"
        secondary: "new_state=secondary"

Services:
  - name: service1
    type: type1
    primary_mode: only_one  # Classic mode - only one primary, others secondary
    url: 
      - http://10.42.58.34:8000
      - http://10.42.58.34:8001

  - name: service2
    type: type2
    primary_mode: many  # New mode - multiple primary allowed, independent control
    url: 
      - http://10.42.58.34:8002
      - http://10.42.58.34:8003

  - name: service3
    type: type1
    image.png
    url: 
      - http://10.42.58.34:8002
      - http://10.42.58.34:8003

  - name: service4
    type: type3
    primary_mode: many
    url: 
      - http://10.42.58.34:8004
      - http://10.42.58.34:8005

  - name: service5
    type: type3
    primary_mode: only_one
    url: 
      - http://10.42.58.34:8006
      - http://10.42.58.34:8007

  - name: service6
    type: type3
    primary_mode: many
    url: 
      - http://10.42.58.34:8008
      - http://10.42.58.34:8009
