name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Run backend tests
      run: |
        cd backend
        npm test
      env:
        NODE_ENV: test

    - name: Run frontend tests
      run: |
        cd frontend
        npm test
      env:
        NODE_ENV: test

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Backend security audit
      run: |
        cd backend
        npm audit --audit-level moderate

    - name: Frontend security audit
      run: |
        cd frontend
        npm audit --audit-level moderate

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install backend dependencies
      run: |
        cd backend
        npm ci

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci

    - name: Run backend linting
      run: |
        cd backend
        npm run lint
      continue-on-error: true

    - name: Run frontend linting
      run: |
        cd frontend
        npm run lint
      continue-on-error: true

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t dominus:test .

    - name: Test Docker image
      run: |
        docker run --rm -d --name dominus-test -p 3001:3001 dominus:test
        sleep 10
        curl -f http://localhost:3001 || exit 1
        docker stop dominus-test
